Do not await modbus 'close()' calls
pymodbus modbus.close returns 'None' and is not async.
Hence, it can not be 'awaited'. This raises the following exception:

   TypeError: object NoneType can't be used in 'await' expression

This commit removes 'await' from all 'close()' calls.